### PR TITLE
PHP8 Support

### PR DESCRIPTION
**Pull request by KartaviK**

### CODE REVIEW

**Comment by Hikariii** [comment]
Nice quick response. There is no way I can verify this works though. I'd like to add some testing before merge.

**Comment by Hikariii** [comment]
For one, there is no stable doctrine/orm release with php8 ability. https://github.com/doctrine/orm/issues/8350

**Comment by janlanger** [comment]
@Hikariii Hi, ORM 2.8 was released few days later with PHP 8 support. Can we help to move this forward?

**Comment by Hikariii** [comment]
A lot had to be changed for php8 compatibility and testing, but all that is now merged in master and released in version 4.3.0:
https://github.com/ScientaNL/DoctrineJsonFunctions/releases/tag/4.3.0
https://packagist.org/packages/scienta/doctrine-json-functions#4.3.0

**Pull request closed without merging**
