### PR TITLE
feat: add support for dbal v4

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by simPod** [comment]
I think this will require too much work to get is working on unsupported php versions. I'm willing to implement this is we drop <8.2 php support.

**Comment by Hikariii** [comment]
Great suggestion! This needs a major version upgrade, removing older unsupported php versions.
Creating a 6.x branch and requiring `php: ^8.1` support looks to me like the way forward.

**Comment by Hikariii** [comment]
> I think this will require too much work to get is working on unsupported php versions. I'm willing to implement this is we drop <8.2 php support.

Dropping php 8.1 is too much for me, since php 8.1 is still supported by Doctrine 3

**Comment by simPod** [comment]
Tests were the worst. CI is green, WDYT?

**Comment by abozhinov** [comment]
When to expect the new release?

**Comment by Hikariii** [comment]
> When to expect the new release?

Release [5.5.0](https://github.com/ScientaNL/DoctrineJsonFunctions/releases/tag/5.5.0) supports orm 3

**Comment by Hikariii** [comment]
> Tests were the worst. CI is green, WDYT?

Looks good, let me see if I can adopt and fix your work after a 5.x compatibility merge

**Comment by Hikariii** [comment]
Closed because this is merged via https://github.com/ScientaNL/DoctrineJsonFunctions/pull/109

**Comment by simPod** [comment]
I'm not as a contributor in release notes at dbal 4 support 🤔 🙃 🫠

**Comment by Hikariii** [comment]
I'm quite sure you are: https://github.com/ScientaNL/DoctrineJsonFunctions/pull/109/commits/b153ee24af6d1e9b75bb2654e7eeb1ea72969162
It is a shared commit.

**Comment by simPod** [comment]
Release notes 
image

**Pull request closed without merging**
